inputs:
    data: 'data/hcp_t1_cpac_all_sites'
    targets: 'data/hcp_sexes_all_sites'
    sites: 'data/hcp_sources_all_sites'
    sex: 'data/hcp_sexes_all_sites'
    age: ''
logging:
    weights_save_folder: './logfiles/weights/'
    comet_experiment_api: 'kYVqzmHEUN7WQLo86k2bZs1Z7'
    comet_project_name: 'fader-net-hcp'
    comet_workspace: 'kondratevakate'
params:    
    site_codes: {'Q04': 1,
  'Q06': 2,
  'Q05': 3,
  'Q11': 4,
  'Q08': 5,
  'Q09': 6,
  'Q03': 7,
  'Q12': 8,
  'Q10': 9,
  'Q07': 10,
  'Q02': 11,
  'Q13': 12,
  'Q01': 13}
  
    dataset_info: 'hcp_compressed_T1'       
    n_sites: 13
    r_seed: 0
    img_size: [64, 64, 64,]
    img_crop: [3, 67]
    pad: [5, 1, 0, 0, 1, 5]
    args: {
    "batch_size" : 64,
    "learning_rate" : 0.0001,
    "D_learning_rate" : 0.00001,
    "n_epochs" : 3000,
    "stop_val_loss" : 0.1,
    # Fadernet
    "img_shape" : [1, 48, 48, 48,],
    "conv_model" : [32, 64, 64, 128, 512,],
    "lrely_slope" : 0.2,
    # disc
    "D_conv_model" : [],
    "D_fc_model" : [512, 128, 64, 64, 32,],
    "D_dropout" : 0.0,
    "D_batchnorm" : True,
    # D_training
    "D_n_upd" : 5,
    "min_lambda" : 0,
    "max_lambda" : 0, #3e-3,
    "pretr_val_loss" : 0, # 0.2, no lambda increment
    "min_val_loss" : 0}
    save_vis_freq: 5 
    

    
    