{
    # opt
    "learning_rate": 0.0001,
    "weight_decay": 0,
    
    # scheduler
    "step_size": 50,
    "gamma": 0.5, # lr *= gamma
    
    # training
    "batch_size": 128,
    "n_epochs": 100,
    "epsilon": 0,
    "n_splits": 10,
    "n_repeats": 1,
    "mode" : "clf",
    
    # Encoding model
    "img_shape": [13,40,48,40,],
    "n_outputs" : 2,
    "conv_model" : [64, 128, 256, 512, 1024,],
    "lrelu_slope" : 0.2,
    "noises" : [0, 0, 0, 0, 0,],
    "n_attrs_outputs" : [4,],
    
    # Discriminator
    "D_conv_model" : [1024,],
    "D_fc_model" : [1024, 512, 256, 128, 64,],
    "D_dropout" : 0.3,
    "D_batchnorm" : True,
    
    # Discriminator training
    "D_learning_rate" : 0.00001,
    "D_n_upd" : 5,
    "D_loop_epochs" : 100,
    "n_pretr_epochs" : 0,
    "min_lambda" : 0,
    "inc_lambda" : 0.00005,
    "max_lambda" : 0.01,
    "lambda_scheduler" : "linear",
    "lambda_gamma" : 10,
} 